apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-new
spec:
  selector:
    matchLabels:
      app: my-new
  replicas: 3
  template:
    metadata:
      labels:
        app: my-new
    spec:
      containers:
      - name: my-new
        image: jayaraju/my-new
        ports:
        - containerPort: 8080
